spring.application.name=demo

# Logging configuration
# logging.level.root=INFO
# logging.level.org.springframework.security=INFO

# MySQL configuration
# spring.datasource.url=jdbc:mysql://mysql:3306/myapp
# spring.datasource.username=myappuser
# spring.datasource.password=strongpassword

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Pepper secret key move this to AWS pswd vault and incorporate rotations
# pepper.secret-key=HHaf2m4Xoz4CWLaOAeLvEdylQd4b7ln/+N0jl1xWK1g=

# JWT secret key move this to AWS pswd vault and incorporate rotations
# jwt.secret-key=3uSMMHFuEN/htd/rEyAwNbLiHuZxuhCI1GnvYxdoW48=

# CSRF secret key move this to AWS pswd vault and incorporate rotations
# csrf.secret-key=Ba+T/GyBWd98k4K9mLZJIQ0R/nZ4Yoff+3JOer7FAa0=